# Generated by Django 5.2.3 on 2025-06-16 00:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dining",
            fields=[
                (
                    "did",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dname", models.CharField(max_length=100)),
            ],
        ),
    ]
