# Generated by Django 5.2.3 on 2025-06-16 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0002_dining"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "fid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                (
                    "dining",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dining.dining"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dining.users"
                    ),
                ),
            ],
        ),
    ]
