# Generated by Django 5.2.3 on 2025-06-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0003_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("code", models.CharField(max_length=6)),
                (
                    "email",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
