# Generated by Django 5.2.3 on 2025-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0004_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="created_at_time",
            field=models.TimeField(null=True),
        ),
    ]
