# Generated by Django 5.2.3 on 2025-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0005_otp_created_at_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created_at_time",
            field=models.IntegerField(null=True),
        ),
    ]
