# Generated by Django 5.2.3 on 2025-06-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0006_alter_otp_created_at_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="token",
            new_name="fcm_token",
        ),
    ]
