# Generated by Django 5.2.3 on 2025-07-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0007_rename_token_users_fcm_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="dining",
        ),
    ]
