# Generated by Django 5.2.3 on 2025-07-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0008_remove_favorites_dining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorites",
            name="fname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
