# Generated by Django 5.2.3 on 2025-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0009_alter_favorites_fname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="fcm_token",
            field=models.CharField(max_length=2000),
        ),
    ]
