# Generated by Django 5.2.3 on 2025-09-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0010_alter_users_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorites",
            name="fname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="favorites",
            unique_together={("user", "fname")},
        ),
    ]
